[package]
name = "json_proc_trait"
description = "defines a trait that json_proc_macro uses (avoids cyclic dependencies)"
version = "0.1.2"
edition = "2021"

authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true