[package]
name = "json_proc"
version = "0.1.0"
edition = "2021"

[dependencies]
json_proc_macro = { path = "./json_proc_macro", version = "0.1.0" }
json_proc_trait = { path = "./json_proc_trait", version = "0.1.0"}

[dev-dependencies]
serde_json = "1.0.128"

[[bin]]
name = "test"
path = ".\\tests\\main.rs"