[workspace]
package.authors = ["littleBitsman"]
package.documentation = "https://docs.rs/json_proc"
package.license = "MIT"
package.readme = "./README.md"
package.repository = "https://github.com/littleBitsman/json_proc"


[package]
name = "json_proc"
description = "provides a proc macro for parsing JSON-like syntax"
version = "0.1.3"
edition = "2021"

authors.workspace = true
documentation.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
json_proc_macro = { path = "./json_proc_macro", version = "0.1.3" }
json_proc_trait = { path = "./json_proc_trait", version = "0.1.3" }

[dev-dependencies]
serde_json = "1.0.128"