[package]
name = "json_proc"
version = "0.1.0"
edition = "2021"

[dependencies]
json_proc_macro = { path = "../json_proc_macro" }
json_proc_trait = { path = "../json_proc_trait" }

[[bin]]
name = "test2"
path = "./tests/main2.rs"