[package]
name = "json_proc"
version = "1.0.0"
edition = "2021"

[dependencies]
json_proc_macro = { path = "../json_proc_macro" }
json_proc_trait = { path = "../json_proc_trait" }

[dev-dependencies]
serde_json = "1.0.128"

[[bin]]
name = "test"
path = ".\\tests\\main.rs"